version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: my_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5012:5000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - my_network

  init:
    build:
      context: ./init
      dockerfile: Dockerfile
    container_name: init_service
    depends_on:
      - app
      - db
    env_file:
      - .env
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
