apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: docker.io/nextcloud:stable-apache
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: nextcloud-configmap
            - secretRef:
                name: nextcloud-secret
            - configMapRef:
                name: postgres-configmap
            - secretRef:
                name: postgres-secret
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 240
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
      restartPolicy: Always
      dnsPolicy: ClusterFirst